name: Release announce
on:
  push:
    branches: [main]

jobs:
  run-release:
    name: Announce
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.65.2
      - uses: taiga-family/ci/actions/setup/node@v1.65.2

      - id: info
        run: |
          echo "version=v$(node -p "require('./projects/ng-polymorpheus/package.json').version")" >> $GITHUB_OUTPUT
          echo "name=$(node -p "require('./projects/ng-polymorpheus/package.json').name")" >> $GITHUB_OUTPUT

      - name: Announce to Telegram
        uses: taiga-family/ci/actions/messenger/telegram/announce@v1.65.2
        with:
          chatId: ${{ secrets.TAIGA_TELEGRAM_CHAT_ID }}
          topicId: ${{ secrets.TAIGA_TELEGRAM_CHAT_THREAD_ID }}
          token: ${{ secrets.TAIGA_TELEGRAM_BOT_TOKEN }}
          version: ${{ steps.info.outputs.version }}
          textLink: ${{ steps.info.outputs.name }}

concurrency:
  group: announce-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
